
OrdererOrgs:
  - Name: Orderer
    Domain: battery.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.battery.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.battery.com
    Template:
      Count: 1
    Users:
      Count: 5